### ISSUE TITLE
Order of the players

### ISSUE THREAD

**Issue by trepik** [marekkukan/liars-dice#1]
Before the game starts, all players should roll their dice to determine the order. (Who plays after who). For example a player with the highest sum of his rolled dice face values should start the game.

**Comment by marekkukan** [comment]
That would be unnecessarily complicated .. what if two players roll the same?

Order is determined automatically (players are randomly shuffled before each game).

**Comment by trepik** [comment]
> players are randomly shuffled before each game

^This is what I basically wanted to achieve, but my formulation was really poor. Thanks for the clarification.
