### ISSUE TITLE
Reveal beahvior

### ISSUE THREAD

**Issue by trepik** [marekkukan/liars-dice#2]
If one reveals some dice, the managers sends back only the values of the yet unrevealed dice. It is a bit confusing when using manual player. One need to keep track of his revealed dice somewhere aside.
I'm not saying the behavior is wrong, just pointing it out, as an issue to think about. Finally I'm adding a log showing the behavior:
```
PLAY 4 1 4 4 1 2
REVEAL 1
PLAY 1 1 4 5 4
BID 4 1
OPPONENT_BIDS 5 1
PLAY 1 1 4 5 4
REVEAL 1
PLAY 6 4 2 6
```

**Comment by marekkukan** [comment]
This behavior is intended. One needs to keep track of his revealed dice anyway, because when he wants to REVEAL again, he must know which dice are already revealed, so that he doesn't reveal the same dice twice.

**Comment by trepik** [comment]
Maybe I'm making things more complicated than necessary, and for computer players it's easy to keep track of their dice. However in a multiplayer game with lost of dice and in a long round, a human player might get easily lost in a long log. The manager sends all unrevealed dice before each turn to each player even if they are the same as in the turn before. Revealed dice could be easily included like this: 
```
PLAY 4 1 4 4 1 2
REVEAL 1
PLAY 1 1 4 5 4 | 1
BID 4 1
OPPONENT_BIDS 5 1
PLAY 1 1 4 5 4 | 1
REVEAL 1
PLAY 6 4 2 6 | 1 1
```

**Comment by marekkukan** [comment]
That's a good suggestion. The protocol was designed to be easily parseable, not to be readable by humans. Check out new manual play and let me know what you think.

**Comment by trepik** [comment]
I like the new manual player, good job.
