### ISSUE TITLE
Bidding to infinity

### ISSUE THREAD

**Issue by trepik** [marekkukan/liars-dice#6]
While developing my player I came across an issue when two players raise their bids to infinity. Shouldn't the game manager call a bid that has count over the total count of dice in play an invalid bid?
Here is an example:
```
manager -> btplayer.py[DavidSwanson]:	PLAY 5 5 5 6 2 2
btplayer.py[DavidSwanson] -> manager:	BID 268 5
manager -> btplayer.py[AliceStraley]:	PLAYER_BIDS DavidSwanson 268 5
manager -> btplayer.py[AliceStraley]:	PLAY 3 5 5 2 3 4
btplayer.py[AliceStraley] -> manager:	BID 269 3
manager -> btplayer.py[DavidSwanson]:	PLAYER_BIDS AliceStraley 269 3
manager -> btplayer.py[DavidSwanson]:	PLAY 5 5 5 6 2 2
btplayer.py[DavidSwanson] -> manager:	BID 269 5
manager -> btplayer.py[AliceStraley]:	PLAYER_BIDS DavidSwanson 269 5
manager -> btplayer.py[AliceStraley]:	PLAY 3 5 5 2 3 4
btplayer.py[AliceStraley] -> manager:	BID 270 3
manager -> btplayer.py[DavidSwanson]:	PLAYER_BIDS AliceStraley 270 3
```

**Comment by marekkukan** [comment]
I thought this would never happen, because players will challenge. But you're right, the manager cannot just assume that.

However, in some cases bidding total count + 1 can be useful, so invalid bid count will start at t.c.+2.
