### ISSUE TITLE
Reveal all dice and then what

### ISSUE THREAD

**Issue by trepik** [marekkukan/liars-dice#7]
There was a situation when player has revealed all of his dice. The manager only sent him a `PLAY` message without a new "roll". Of course there is nothing wrong with that but the program stuck in some forever loop. I'm just reporting it, not sure where the looping was. I'm gonna investigate more later.

**Comment by marekkukan** [comment]
Interesting. When you reveal all dice with manual player, game continues normally. Looks like the player got stuck expecting some dice on stdin. Let me know when you find the problem.

**Comment by trepik** [comment]
Yesterday I finally resolved the issue. It had nothing to do with the manager, nor with the sole `PLAY` message. It was an infinite recursion in my player causing the freeze. A move from the player never came and the manager did not shut him of.
