### ISSUE TITLE
Error in challenge evaluation or player had shows wrong numbers

### ISSUE THREAD

**Issue by trepik** [marekkukan/liars-dice#8]
I was playing a bit with manual player and came across a weird end of the game. See the log:
```
NEW_ROUND 7 1 0
PLAYER_BIDS 1 1 6
PLAY 3 6 1 1 3 1 3
b 6 3
PLAYER_CHALLENGES 1
PLAYER_HAD 1 1
YOU_WIN
```
According to the log there were `3 3s` and `4 1s` which makes total of `7 3s` and I should have lost the round.

**Comment by marekkukan** [comment]
You bid 6 3, which means "at least six threes", and there were 7 3s, so you were right, and therefore you win.

**Comment by trepik** [comment]
You're right, my bad.
